# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  pull_request:
    types:
      - closed
    branches:
      - 'master'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  merge_job:
    # this job will only run if the PR has been merged
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - name: Delete merged branch
      uses: koj-co/delete-merged-action@master
      with:
        branches: "!master, !development, !hot-fix*, !hotfix*, *"
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
